from sqlalchemy import Column, String, Integer, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class ImageAnalysisResult(Base):
    """
    Represents the result of an image analysis in the database.

    Attributes:
        id (int): The unique identifier for the analysis result.
        image_hash (str): The SHA-256 hash of the analyzed image, used to check for duplicates.
        caption_text (str): The caption generated by the image analysis model.
        caption_confidence (float): The confidence score associated with the generated caption.
    """
    __tablename__ = 'image_analysis_results'

    # The primary key for the image analysis result
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # The unique image hash for this analysis result
    image_hash = Column(String(64), unique=True, nullable=False)
    
    # The generated caption for the image, can be null if not generated
    caption_text = Column(String(255), nullable=True)
    
    # The confidence score for the generated caption, can be null if not available
    caption_confidence = Column(Float, nullable=True)
